# Generated by Django 2.0.6 on 2018-08-02 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20180802_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='apellidos_admin',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='nombre_admin',
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellidos_users',
            field=models.CharField(default="garcia", max_length=50, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$|\\d*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='celuda',
            field=models.IntegerField(default=12345678, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='correo_participarnte',
            field=models.EmailField(default="yitmar.14151819@hotmail.com", max_length=254, validators=[django.core.validators.RegexValidator(message='solo se permiten correos hotmail.com o gmail.com', regex='^[a-zA-Z]*@hotmail.com|[a-zA-Z]*@gmail.com$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_participacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre_user',
            field=models.CharField(default="leonardo", max_length=50, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$|\\d*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='p00',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='solo se aceptas numeros', regex='^[0-9]{6,8}')]),
        ),
    ]
