# Generated by Django 2.0.6 on 2018-06-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dificultad',
            fields=[
                ('id_dificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dificultad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pregunta', models.CharField(max_length=100)),
                ('valor_pregunta', models.IntegerField()),
                ('pregunta_imagen', models.ImageField(upload_to='')),
                ('id_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.dificultad')),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_respuesta', models.CharField(max_length=100)),
                ('tipo_respuesta', models.BooleanField()),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_pregunta',
            fields=[
                ('id_tipo_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_pregunta', models.CharField(max_length=20)),
                ('id_sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.tipo_pregunta'),
        ),
    ]
