# Generated by Django 2.0.6 on 2018-06-14 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='id_dificultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.dificultad', validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id_tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.tipo_pregunta', validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nombre_pregunta',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='valor_pregunta',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[0-9]{0,1}')]),
        ),
    ]
