# Generated by Django 2.0.6 on 2018-06-14 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_auto_20180614_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='valor_pregunta',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[0-9]{2}')]),
        ),
    ]
