# Generated by Django 2.0.6 on 2018-08-10 18:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prueba', models.CharField(max_length=50)),
                ('durancion_pruaba', models.IntegerField(validators=[django.core.validators.RegexValidator(message='solo se acepta solo numero', regex='^[0-9]{0,2}')])),
                ('valor_prueba', models.IntegerField(validators=[django.core.validators.RegexValidator(message='solo se acepta solo numero', regex='^[0-9]{0,2}')])),
                ('cantidad_pregunta', models.IntegerField(validators=[django.core.validators.RegexValidator(message='solo se acepta solo numero', regex='^[0-9]{0,2}')])),
                ('tipo_prueba', models.CharField(blank=True, max_length=50)),
                ('arreglo_preguntas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('arreglo_valor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.dificultad')),
            ],
        ),
        migrations.CreateModel(
            name='prueba_presona',
            fields=[
                ('id_prueba_presona', models.AutoField(primary_key=True, serialize=False)),
                ('id_admin', models.IntegerField()),
                ('id_prueba', models.IntegerField()),
            ],
        ),
    ]
