# Generated by Django 2.0.6 on 2018-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prueba', models.CharField(max_length=50)),
                ('durancion_pruaba', models.IntegerField()),
            ],
        ),
    ]
