# Generated by Django 2.0.6 on 2018-06-13 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='fecha_participacion',
        ),
        migrations.AlterField(
            model_name='participante',
            name='tefelono_participante',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='el campo acepta solo numeros', regex='^[0-9]{10}')]),
        ),
    ]
