# Generated by Django 2.0.6 on 2018-06-14 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180613_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='apellidos_participante',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$|\\d*$')]),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nombres_participante',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='solo se aceptas letras', regex='^[a-zA-Z]*$|\\d*$')]),
        ),
    ]
