# Generated by Django 2.0.6 on 2018-06-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nota_evaluacion', models.IntegerField()),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participante')),
                ('id_sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.sub_categoria')),
            ],
        ),
    ]
