# Generated by Django 2.0.6 on 2018-06-28 19:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('arreglo_preguntas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('arreglo_respuesta', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('nota_evaluacion', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participante')),
            ],
        ),
    ]
