# Generated by Django 2.0.6 on 2018-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha_presentacion',
            field=models.DateField(auto_now=True),
        ),
    ]
