# Generated by Django 2.0.6 on 2018-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha_auditoria', models.DateField()),
                ('modulo', models.CharField(max_length=20)),
                ('direccion_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
